<?php
session_start();
include 'config/config.php';
include 'config/functions.php';

$page_title = 'Home - ' . SITE_NAME;
$page_desc = 'AI-Powered WhatsApp API Automation Platform';

include 'includes/header.php';
?>

<section class="hero">
    <div class="container">
            <div class="hero-content">
                        <h1>AI-Powered WhatsApp Automation Platform</h1>
                                    <p>One intelligent platform to automate your <span class="highlight">Marketing</span>, <span class="highlight">Sales</span> and <span class="highlight">Customer Support</span> on WhatsApp.</p>
                                                <p class="subheading">Powered by Official WhatsApp Business API</p>

                                                                        <div class="cta-buttons">
                                                                                        <a href="admin/" class="btn btn-primary">Book a Demo</a>
                                                                                                        <a href="pages/pricing.php" class="btn btn-secondary">Get Started</a>
                                                                                                                    </div>
                                                                                                                            </div>
                                                                                                                                </div>
                                                                                                                                </section>
                                                                                                                                
                                                                                                                                <section class="automation-features">
                                                                                                                                    <div class="container">
                                                                                                                                            <h2>Automate Everything With Powerful Workflows</h2>
                                                                                                                                                    
                                                                                                                                                            <div class="automation-grid">
                                                                                                                                                                        <div class="feature-tag">
                                                                                                                                                                                        <span class="label">Route Chat to</span>
                                                                                                                                                                                                        <span class="value">Sales Team</span>
                                                                                                                                                                                                                        <span class="condition">if High Intent</span>
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                            <div class="feature-tag">
                                                                                                                                                                                                                                                                            <span class="label">Automate if</span>
                                                                                                                                                                                                                                                                                            <span class="value">Abandoned Cart</span>
                                                                                                                                                                                                                                                                                                            <span class="condition">after 30 Minutes</span>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                    <section class="cta-final">
                                                                                                                                                                                                                                                                                                                                        <div class="container">
                                                                                                                                                                                                                                                                                                                                                <h2>Ready to Transform Your Business Communication?</h2>
                                                                                                                                                                                                                                                                                                                                                        <p>Join thousands of businesses automating customer conversations on WhatsApp.</p>
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                        <div class="cta-buttons">
                                                                                                                                                                                                                                                                                                                                                                                    <a href="admin/" class="btn btn-primary">Book a Demo</a>
                                                                                                                                                                                                                                                                                                                                                                                                <a href="pages/pricing.php" class="btn btn-secondary">Get Started Free</a>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                            <?php include 'includes/footer.php'; ?>
